version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: control_panel_db
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - controlPanel_network

  tomcat:
    image: ghcr.io/cows-inc-sa-fall23/control_panel:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - controlPanel_network
      
volumes:
  db_data: {}

networks:
  controlPanel_network:
    driver: bridge