name: SSH into VM and Execute Commands

on:
  push:
    branches:
      - DockerDemoIntergration

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.USER_KEY }}

      - name: print env
        run: |
          echo $SSH_PRIVATE_KEY
          echo $SSH_USERNAME
          echo $SSH_HOSTNAME

      - name: Setup SSH directory and keys
        run: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

      - name: Test DNS resolution
        run: nslookup bds-g11-n0.uvm.sdu.dk

      - name: Execute commands over SSH
        run: |
          ssh -vvv -i ~/.ssh/id_rsa micpe18@bds-g11-n0.uvm.sdu.dk "echo 'Hello World'"
