name: SSH into VM and Execute Commands

on:
  push:
    branches:
      - DockerDemoIntergration

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}

jobs:
  ssh:
    runs-on: ubuntu-latest
    environment: SSH_PRIVATE_KEY
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print env
        run: |
          echo $SSH_PRIVATE_KEY
          echo $SSH_USERNAME
          echo $SSH_HOSTNAME

      - name: Use SSH keys
        run: |
          echo "Using SSH key for user $SSH_USERNAME at host $SSH_HOSTNAME"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Execute commands over SSH
        run: |
          ssh -i id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }} "echo 'Hello World'"
